- name: Deploy UniFi Container
  become: yes
  docker_container:
    name: unifi
    pull: yes
    image: "linuxserver/unifi-controller"
    env:
      MEM_LIMIT: "384M"
    ports:
      - "3478:3478/udp"
      - "6789:6789"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "10001:10001/udp"
    volumes:
      - "unifi-config:/config"
    restart_policy: "unless-stopped"
