- import_playbook: bootstrap.yaml

- hosts: localhost
    - role: base-devel
    - role: chezmoi
    - role: docker
    - role: etckeeper
    - role: fwupd
      when:
        - ansible_facts['virtualization_role'] == "host"
    - role: haveged
    - role: jq
    - role: linux-lts
    #- role: makepkg # TODO: Does not exist
    - role: neovim
    - role: nmap
    - role: openvpn
    #- role: pacman # TODO: Does not exist
    - role: pkgstats
    - role: vim
    - role: wireguard-arch
    - role: wireguard-lts
    - role: wireguard-tools
