---
- hosts: localhost
  become: yes
  roles:
      - role: intel-ucode
        when: "'GenuineIntel' in ansible_processor"
      - role: amd-ucode
        when: "'AuthenticAMD' in ansible_processor"
      - role: neovim

# vim: et sw=2 ts=2
