- name: Install docker
  pacman:
    name: docker
    state: present

- name: Enable docker service
  service:
    name: docker
    enabled: yes

- name: Start docker service
  service:
    name: docker
    state: started

# vim: et sw=2 ts=2:
