- name: Install pkgstats
  pacman:
    name: pkgstats
    state: present

- name: Enable pkgstats service
  service:
    name: pkgstats
    enabled: yes

- name: Start pkgstats service
  service:
    name: pkgstats
    state: started

# vim: et sw=2 ts=2:
